---
title: "Thinking about a Masters but not sure what to ask"
output:
  html_document:
    google-analytics: "G-JFTXYY710V"
    toc: true
    toc_float:
      collapsed: true
    toc_depth: 3
    number_sections: false
    theme: readable
    highlight: espresso
  pdf_document:
    toc: true
    toc_depth: '3'
  word_document:
    toc: true
    toc_depth: '3'
---

<style>
h1:not(.title), #TOC > ul.tocify-header > li:first-child {
  font-weight: bold; 
  color: green; 
}

h2, #TOC ul.tocify-subheader[data-tag="2"] > li.tocify-item {
  color: blue; 
}

h3, #TOC ul.tocify-subheader[data-tag="3"] > li.tocify-item {
  color: purple;
  font-variant: small-caps; 
}

body{
  font-family: Arial;
}

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This blog

This document was last updated on `r Sys.Date()` and was written and edited by [Dr Phil McAleer (School of Psychology and Neuroscience, University of Glasgow)](https://www.gla.ac.uk/schools/psychologyneuroscience/staff/philipmcaleer/){target="_blank"}. 

This is a series of questions that a person might want to consider asking, or finding information about, when thinking about what Masters programme is right for them in the UK. For me, when thinking back to my undergraduate days, I didn't really know what a Masters or postgraduate study was about. I had heard about it, and knew others were thinking about doing it, but it was all a bit of a mystery. Nowadays, as an academic lead for an MSc programme, I still talk to a number of undergraduate students who are not quite sure. As such, and to try and reduce a barrier, I wanted to put together "something" that introduced some of the main terminology and gave people an idea of some of the things/questions they might want to think about when looking at Masters. Below is a series of questions and why you might want to think about them - I am definitely not trying to answer these questions and really just focusing on why you might ask them. I really hope it helps and there is instructions for feedback at the end; I would dearly love to hear your comments.

**Please note:** 

* if viewing this blog on a phone, use landscape orientation rather than portrait for better functionality. 
* you can download a word version of this blog by [clicking this link](https://philmcaleer.github.io/thinkingmasters/index.docx)
* this is a living document and may be updated at various intervals.

# What is a Masters Programme in the UK?

A Masters programme is typically a one year degree that is undertaken after you complete an undergraduate degree in a related subject. For example, if you have completed an undergraduate degree in Psychology, you might then consider a Masters programme that will develop and enhance the skills you learnt during your Psychology undergraduate. 

Some Masters programmes are designed to be general, such as a Masters in Research Methods in Psychology, and these will look to enhance your skills across a range of different approaches - e.g. building up your qualitative and quantitative skills across various sub-fields. Other Masters are designed to be more targeted towards a specific area, such as a Masters in Clinical Psychology, and these will start to really specialise your understanding and knowledge in a particular area, based on what you will have already covered in your undergraduate. 

## PGT, PGR, MSc, MRes & PhD: What's the difference?

There is always a lot of acronyms and abbreviations involved and these can be very confusing at first. To summarise, the main ones that you may come across when exploring a Masters are: 

* **PGT:** postgraduate taught 
* **PGR:** postgraduate research 
* **MRes:** Masters by Research 
* **MSc:** Masters of Science
* **MSc Conversion:** Masters of Science Conversion
* **MSc ODL:** Masters of Science Online Distance Learning
* **PhD:** Doctorate of Philosophy

Sticking with the example of Psychology, this is considered a science in UK Universities and as such a lot of the Masters programmes you might be considering will be referred to as an MSc - for example, an MSc in Research Methods of Psychological Science. More often than not, these MSc programmes are considered to be PGT - postgraduate taught - meaning that the programme has a number of modules that you have to complete, along with a dissertation (i.e. a project), just like you did in your undergraduate.

Alternatively, some Masters will be referred to as MRes and these will commonly have no, or very few taught modules, and the majority of the academic year will be spent carrying out and writing up a dissertation. An MRes might be considered either Postgraduate Taught (PGT) or Postgraduate Research (PGR) depending on how much teaching there is on the programme.

An MSc Conversion, on the other hand, is usually an accelerated version of an undergraduate programme and is designed for students who have an undergraduate degree in one subject and want to now have a qualification in a rather different subject. For example, a student who has an undergraduate degree in History and now wants to have a future role in Psychology, and so they might take an MSc Conversion to give them that qualification in their new field.

Normally, an MSc, an MRes and and MSc Conversion are on-campus programmes, in that you go to the University campus each day and take part in in-person lectures, seminars, labs and/or tutorials. In contrast, and MSc ODL is a Masters programme that is conducted online (ODL - Online Distance Learning). These are usually designed for students who have full-time jobs or personal commitments and have only a specific and limited time each day, week and semester for their studies. The MSc ODL is usually conducted over a longer time-frame (e.g. three years rather than one year) and is often considered as part-time education rather than full-time. The main difference though is really that all classes are held online or through recorded videos.

Finally, an MSc and an MRes can be a stepping stone towards starting a PhD (which is also considered part of PGR as it is postgraduate and research-based). This blog wont discuss PhDs but the MSc programme team at the University you are considering should be able to advise.

## Programme, Course or Module: What's the difference? 

It can be confusing when looking at the prospectus of various Universities as the terminology may change and the same word may be used to mean different things at different Universities. One area that this tends to happen is in how we use the terms programme, course and module. Whilst we can’t guarantee this blog will clarify this issue, we will try to use a consistent terminology to help orientate you through the information. As such, for this blog:

* **Programme:** the overall MSc that you are applying for and looking to complete. For example, an MSc in Nutrition, an MSc in Research Methods of Clinical Psychology, or an MSc in the Science of Learning. 
* **Module:** the components of study that you take to complete the MSc. For example, if the programme is the MSc in Research Methods of Clinical Psychology, then you may take a module in Qualitative Research Methods, a module in Quantitative Research Methods, a module in Psychometrics etc. 
* **Course:** Well the problem with the word "course" is that for some it means the programme and for others it means the modules within a programme. To avoid confusion we will avoid using "course".

So that seems fairly straightforward, a programme is made up of a collection of modules, right? Right! Except that some Universities may call the programme, the course, and other Universities might call modules, the courses! Confusing we know! Ultimately, however, there will be the overall concept of the MSc - an MSc in … - and it will be achieved through completing a series of components, and for the remainder of this blog we will refer to the concept of the MSc as the Programme, and the components as Modules.

## Core vs Optional modules: What's the difference?

The last thing to know before we start looking at questions is the difference between core and optional modules. This one is fairly straightforward:

* **Core:** These are the modules that you have to take in the Masters. Every student on the programme will be required to complete all the core modules. The other name you might see for these modules, rather than core, is mandatory. For example, the dissertation in your Masters will likely be core/mandatory.
* **Optional:** These are the modules that you can choose between to complete your overall programme. Not every student will take every optional module as it really comes down to interests and personal motivation for doing the Masters.

# What questions to ask? 

Hopefully you now have an understanding about the different abbreviations and the differences in the types of Masters programmes, and the difference between a programme and a module, etc, and are now finally at the point of looking to ask some questions about the Masters you are interested in.  
So let’s assume you were thinking of applying for an PGT MSc - i.e. ones with a large component of taught modules - what sort of questions would we recommend asking? 

Note: As above, the answers we provide to the below questions are the thinking and reasoning behind why you might want to ask that question, and not specifically providing an answer to these questions. By the end of this piece you should hopefully have an idea about what to ask, why, and who to ask it to!

## What is the divide of the dissertation as well as core and optional modules in terms of credit? 

In the UK, most MSc programmes are made up of 180 credits. How that 180 credits is split across the different modules will vary and this might help you think about how your time will be spent - as above, some modules will be considered core, meaning that you have to take those modules, and others will be considered optional, meaning that you can choose which ones you take up to a certain limit of credits. Let’s look at an example: 

* 60 credits for the Dissertation 
* 90 credits of Core Modules 
* 30 credits of Optional modules 

The above programme would mean that there will be a certain number of modules you have to take, let’s say 5, and they add up to 90 credits - let’s say that 90 credits is made up of four 20 credit modules and one 10 credit module (4x20 + 1x10 = 90). There is then 30 credits from optional modules where you get to choose what you take - let’s say three modules of 10 credits each (3x10 = 30) from a choice of six optional modules. And then you have the dissertation (your project), worth 60 credits, on top of that giving a total of 180 credits (60 + 90 + 30 = 180). 

As you can see, knowing how the course is divided in terms of credits can give you a good idea of what you have to take and what you can choose from. The more optional modules there are, and the more optional credits you can take, the more you can tailor your MSc to your own interests. Conversely, the more core credits there are the less choice you have. 

Just to add however, some programmes need to have a large component of core credits for accreditation purposes - a governing body says that every student who wants to work in a specific area must have covered certain topics for that programme to be recognised by the governing body - and so part of the decision is about thinking about what you want to do with the MSc afterwards as well. A Conversion MSc for example is likely to have a lot of core components as students have to reach a similar standard to students who had completed an undergraduate programme in that field.

## Where can I see all the core and optional modules for the coming year? 

We all have our own interests and in some programmes you will be able to tailor your degree more towards your interests whereas in other programmes you will have less free choice. You will want to have a look at the modules that are determined as core, or mandatory, and the modules that are determined as optional. The more options that you are allowed to take, and the wider range of options that a programme has, the more you can tailor your degree to your own interests. For that reason you will want to try and see a list of all the core and optional modules on offer. The best place is usually the webpage for the Programme on the University’s prospectus; and in particular their postgraduate prospectus. The prospectus is effectively an index of all the programmes taught at that University and it will likely have a breakdown of each programme. Just to note that most prospecti are online these days but if you did want a physical copy, emailing the admissions teams for instructions would be a good start if it isn’t obvious from the webpages.

One thing to note about the details on webpages is that they are indicative of what the programme will be like when you start, and not necessarily the exact programme. They will be very very similar but sometimes things happen and last minute changes to programmes have to be made. The academic team running a programme will most likely make you aware of any changes before the start of the programme so you are fully informed.

## Where can I see the requirements for pass, distinction and merit (or the local equivalent)? 

Going into any programme you will want to know what do you need to do to achieve the Masters. For some, completing the MSc and obtaining an overall pass is their goal, but for others they might want to achieve a certain level of pass. Often MScs use the achievement levels of Distinction, Merit and Pass, with Distinction being considered the highest level, and the difference being based on the overall grade across modules and often a project or large piece of individual work. It is essential, in any programme, to know what is the requirement to obtain a Pass, and ultimately obtain the MSc, but it can help to know in advance what are the requirements for other levels if that is your goal. Again, the admissions team or programme team should be able to point you to these requirements.

If I can digress for one second, as a programme lead I speak to a lot of students about their goals within an MSc, and whilst I hugely respect the notion of obtaining the highest achievement level you can, I would always encourage everyone to set their goal as to pass the Masters and to focus more on the skills, knowledge and experience you obtain in the programme. In the long run, the personal development that you can evidence will be what will help you on to the next step of your career path! 

## When will I be allocated a supervisor for my Dissertation? 

Often a key part of an MSc is the Dissertation, or some large piece of individual work. This is usually completed under the guidance of a supervisor within the University where you are doing the MSc. At what point in the year a student starts their Dissertation is likely to vary from programme to programme with some starting on day one of the programme and some requiring you to have reached a certain standard or completed a certain amount of modules before starting the Dissertation. Given the large amount of work involved in the Dissertation, knowing when you will be allocated a supervisor and when you will start the Dissertation itself can help give you an idea of how to plan your year. 

## How much say will I have in choosing my Dissertation supervisor?

Often students choose a programme based on the topics covered or the people within a School and they may have specific ideas about who they want to work with on their project. Whilst schools often try to accommodate students and match their interests with potential supervisors it is not always possible for various reasons - schools may run multiple programmes and some supervisors are used on certain programmes (depending on the focus of the programme) and not others; staff may not have the capacity for running dissertations in a given year depending on other commitments that come as part of their job; staff may have a limited allocation for teaching dissertation projects and those spaces are already full. As a student it would be useful to know, going into the programme, what is the allocation process for matching students with supervisors - random, free choice, first-come-first served, or an alternative process - to help people avoid joining a programme with an unrealistic expectation of who they will work with.

## How much say will I have in choosing the topic of my Dissertation? 

Similar to the idea of choosing who you will work with on your Dissertation project, you will want to know how much say you have in deciding the topic of the project. As potential postgraduate students people have spent three or four years developing interests and often want to carry those interests through into the Masters; we are often encouraged to start moving towards a specialism after all! Again, Schools often try to match students with supervisors of similar interest but that isn't always possible and a programme team will be able to give you some guidance on how the topic of a dissertation is decided. In my experience the best topics come through flexibility - from both the supervisor and the student - but it is also the case, depending on the topic, that the supervisor has to have full say in how a project is run (e.g. fMRI where there is a great cost per project). 

One thing to keep in mind, even if your dissertation is in an area you have never worked in before, again the skills and knowledge that you develop in the process are probably the most important area to focus on at this stage. Many researchers will tell you that they would rather hire someone who has many well developed skills even if they don't know much about a topic, as opposed to someone who knows everything about a topic but with little skill, as a student quickly can learn about a topic through reading but skills take a lot more time to develop. So, in short, even if working on a topic that would not be your first choice, you still have a lot to learn from the experience! 

## In the taught modules, what percentage of assignments are coursework and what percentage of modules are assessed through exams? 

Here, by coursework, we mean perhaps an essay or review you are asked to write for a module, submitted just after the module, based on the topics covered - you will have a lot of time to work on this piece and when and how you work on it is up to you. By exam we mean the classic sense of a set assignment being opened at a specific time that you have to complete in a set duration. More often than not, these days, you will find that programmes use a mix of coursework and exams, with perhaps a slight swing towards coursework being more common. Every student has their own preference with some loving the extra time on coursework and others preferring the "just get it done" approach of an exam. Knowing the assignment structure in advance can help a student get an idea of how they will show their knowledge and skill development and whether the approach chosen by a school fits with how the student feels they perform best.

## In taught modules, will exams be held online or in-person?

Since the Covid pandemic there has been an increase in online exams, moving away from large halls of desks with all students taking the exam at the same time in the same place. However, with the increased availability of AI there has been a move back towards in-person exams; partly as a means of ensuring that the work produced is genuinely the students. The approach by each University is changing all the time and it will probably be a few more years before a "standard" approach is settled upon, if Universities ever do go back to a "standard" approach; there are a variety of reasons why one module/assignment might be better assessed online or in-person or a mix. All that said, the approach is something that a programme team will be able to tell you but it will be caveated with "to the best of our knowledge at the start of the year" as we are all now wary of our worlds changing rapidly to give anything definitive many months in advance.

Again, to digress, it is worth mentioning that a school's approach to assessment is something that a whole team of people spend many meetings and conversations discussing. However you are assessed on a programme you can be assured that the team have looked at every option available and have decided that the approach they use is the best available to them to help you show your development.  

## What sort of support is there in place for people with disabilities or neurodivergent students? 

Universities are very aware of diversity and inclusion these days and one place to hear about these steps would be either the local Student Representative Council and/or the University Disability services. Often both these bodies will have webpages detailing all the opportunities and help available to people, and a programme team or an admissions team will be able to point you towards their webpages. In addition, these groups will normally have a means of contacting them directly and asking any questions you have in advance of applying. At the school level, there is likely to be a specific person who can be contacted and open to questions about the accommodations within a specific school; again a programme team can point you in the right direction here.

## Is there a Postgraduate Open Day that I could attend to get to know the campus? 

Again most likely one for the admissions team or the programme team but an Open Day is a great way to get to know a place, to check out the facilities and speak to members of the team. It is worth keeping in mind that when you are choosing a programme, you are almost interviewing the University and the School to see if it is the place for you - do they cater for your needs and your interests? do you feel like you could be supported here? A one year Masters is a challenging year so you want to make sure that you are going to be well supported; both academically and personally. 

## What sort of community events are there or opportunities to meet and network with other students and staff? 

Part of a Masters is making connections and starting that network of people you may want to collaborate with in future work. Likewise, and related to the idea about Open Days, you are going to need support from staff and fellow students throughout the year. Putting both these together, it can be really useful to know in advance if there is something like an active social group or a society for organising postgraduate events and get-togethers where students and staff can chat. In addition, you might want to consider if there is an active seminar series or journal club that you can get involved in and attend; a Masters is about soaking up knowledge and learning about different approaches, and so events like seminars and workshops are a great place to do this as well as get chatting to others.

## Is it possible to speak to current students or alumni? 

One of the best bits of advice I ever heard (and sadly I can't remember who I heard it from first) was, when applying to a PhD, ask to speak to other members of a lab without their supervisor present. If the supervisor is happy to accommodate this then there is a good chance there is nothing they are worried about that their lab would say. If the supervisor does not accommodate this then I would consider this a sign that there may be things the supervisor would not like their lab to say to a prospective student and you would need to consider if that is the right person for you to work with. 

I personally think that it can be a good idea to take a same approach with a Masters that you are applying to - if the programme team is worried about what their students would say then perhaps it is not the programme for you. If however the programme team are fine with what the students say regardless then maybe it shows a reflective and honest programme team. Obviously it would be good to speak to two or three students if possible as you always want to take into consideration personal bias, but any input you can receive from fellow students, who have been through or are going through the programme, will help you prepare and give you a better sense of what studying on your chosen programme is like.

## Is there a list of available funding opportunities that I can look at?

Most programmes and Universities these days will have a list of funding opportunities - grants and scholarships - on their webpages. They are sometimes quite difficult to navigate and tend to have a lot of different and varying requirements. If you are struggling to find the funding opportunities, this is usually one that the admissions team or the student representative council will be able to help with.

## Is there an option to do the programme part-time or start at a different time of year?

Each person has their own pressures in life and other commitments outside of studying and just knowing what the available options are is beneficial. Again this information will normally be contained on a webpage for the programme but if in doubt, the programme team or admissions team will normally be able to answer this. Part time study on a Masters usually would mean extending the degree from one year to two or three, with the taught modules being spread out over the first year or two, and the dissertation being the final year. This allows for people who, for instance, have to maintain a job or family life at the same time as studying, and just gives them that flexibility. Likewise, you might find programmes that say they have two intakes - usually around September and January. This means that the programme starts twice a year and you can choose which of the two streams works better for you - the content will be the same, it will just be spread differently across the year.

**End of Questions**

# Feedback

I really hope that these questions and ideas have been useful to you and you are more than welcome to share this document with others if you like; it is available under CC-BY-SA-4.0.  In addition, it would be great to hear of any comments or additional questions you would suggest I include. I am more than happy to receive any comments and ideas so please do either email them to me at philip.mcaleer@glasgow.ac.uk or, if you prefer anonymous comments, feel free to use this anonymous form: [Provide feedback on this document](https://forms.office.com/e/jWLwbbUBFq){target="_blank"}
